### Traer tareas
GET http://localhost:3000/api/tasks

### Crear tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "tittle": "nuevo titulo",
    "description": "nueva descripcion",
    "image": "www.url.com"
}
### Modificar tareas
PUT http://localhost:3000/api/tasks/1
Content-Type: application/json

{
    "tittle": "nuevo nuevo",
    
}

###Eliminar

DELETE http://localhost:3000/api/tasks/3